### PR TITLE
Horizon reliability improvements

### PR DESCRIPTION
**Pull request by IgorWolkov**
Add retry logic for failed futures.
Add multi host round robin requests for recoveries on failed responses.

### CODE REVIEW

**Comment by Synesso** [comment]
Thanks @IgorWolkov. This looks promising. I'll try to review in more detail over the weekend.

Try out the integration tests (`sbt it:test`), as there are a couple of failures at this time.

**Comment by IgorWolkov** [comment]
> Thanks @IgorWolkov. This looks promising. I'll try to review in more detail over the weekend.
> 
> Try out the integration tests (`sbt it:test`), as there are a couple of failures at this time.

Thank you, will check.
We are also looking into `cats` IO + `http4` client + `fs2`. `cats-effects` already has `cats-retry` lib. I've built `paginator` for stellar with cats IO, if we get good results, I'll share it with the community.

**Comment by Synesso** [comment]
I've rebased to current master. Unfortunately I didn't get a chance to look at the integration test failures either, but they look curious. The standalone network integration tests is horribly convoluted, so I'll try to figure that out. Sorry for the delay.

**Comment by Synesso** [comment]
I fixed an issue that was underlying most of the failures. There remains a problem with calling Friendbot, which I'll look at later today.

I commented out `MultiHostCaller` with a TODO to raise this in a separate PR. Please include some notes about what purpose it serves and test coverage.

**Pull request merged**
